export const ActionTypes = {
  // action types
  FETCH_USERS: "FETCH_USERS",
  SELECTED_USER: "SELECTED_USER",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
  ADD_USER: "ADD_USER",

  SET_MESSAGE: "SET_MESSAGE",
  REMOVE_MESSAGE: "REMOVE_MESSAGE",

  SET_CATEGORY: "SET_CATEGORY",
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  SELECTED_CATEGORY: "SELECTED_CATEGORY",
  REMOVE_SELECTED_CATEGORY: "REMOVE_SLECTED_CATEGORY",
};
